[package]
name = "dummy_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc"
toml = "0.7.4"
serde = "1.0.136"
serde_derive = "1.0.136"



[env]
ROCKET_PORT=9879